name: Release CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew test

  release:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Decode Keystore
        env:
          SIGNING_STORE_DIR: ${{ secrets.SIGNING_STORE_PATH }}
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          mkdir -p $SIGNING_STORE_DIR
          echo $ENCODED_STRING | base64 -di > "${SIGNING_STORE_DIR}/custom.jks"
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble release build
        env:
          SIGNING_STORE_PATH: ${{ secrets.SIGNING_STORE_PATH }}/custom.jks
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew app:bundleRelease
